# Generated by Django 4.2.6 on 2024-05-24 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_categoria_nombre_alter_subcategoria_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='categoria_madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categorias', to='productos.categoria'),
        ),
    ]
