# Generated by Django 4.2.6 on 2024-05-25 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_categoria_categoria_madre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['categoria', 'nombre']},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='subcategoria',
        ),
        migrations.DeleteModel(
            name='Subcategoria',
        ),
    ]
