# Generated by Django 4.2.6 on 2024-05-25 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_options_remove_producto_subcategoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['categoria_madre', 'nombre']},
        ),
    ]
