# Generated by Django 4.2.6 on 2024-05-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_categoria_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, default='', max_length=300, verbose_name='Descripción del producto'),
        ),
    ]
