# Generated by Django 4.2.6 on 2024-06-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_marca_producto_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(default='', max_length=60),
        ),
    ]
