# Generated by Django 4.2.6 on 2024-07-17 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_remove_producto_marca_producto_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.marca'),
        ),
    ]
