# Generated by Django 4.2.6 on 2024-07-17 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_remove_carrito_cantidad_carrito_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='nro_orden',
        ),
    ]
